### ISSUE TITLE
code occurs when we left order bump schedule blank

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#27]
os: window10
wp version:5.8
wc version: 5.6
version: 1.4.3
path: save order bump
description: when we left order bump schedule blank and save it, then code occurs.
![code error in schedule order 2021 08 18-10_16_24](https://user-images.githubusercontent.com/86113814/129838673-954f2ad5-7622-48c5-a12e-760beaac2cfc.png)

**Comment by MohdFaisalAliKhan-Cedcoss** [comment]
RESOLVED

**Comment by MohdFaisalAliKhan-Cedcoss** [comment]
I have checked and this notices shows in the older version of the plugin as well and this update has nothing to do with it, notice is shown only for the first time because the way this plugin has been designed , 0 is assigned when the field is left empty but when the page is refreshed 'Daily' is assigned.
