### ISSUE TITLE
value in offer price get disappear when we click on discount selectbox 

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/upsell-order-bump-offer-for-woocommerce#29]
os: window10
wp version: 5.8
wc verison: 5.6
version: 1.4.3
path: save order bump
description: when we set 50 in discount % and then we click  on discount% box then the value get disappear.
https://nimb.ws/QCpf9V

**Comment by MohdFaisalAliKhan-Cedcoss** [comment]
I have changed the way it worked, the value is preserved if the user switches between fixed value and discount feature. But if the user switches to 'No discount ' option and back to fixed or percent from it the value will not be preserved because the functionality of 'no discount' option depends on this feature, the field has to be empty with 'none' written inside of it while the Order bump is saved so that our third option can work properly.

**Comment by MohdFaisalAliKhan-Cedcoss** [comment]
Resolved
